import { createAudioPlayer, type AudioPlayer } from 'expo-audio';
import { configureAudio } from './sound';

/**
 * The background tune: one looping player, generated by scripts/generate-sounds.mjs.
 *
 * Like the effects, music is a courtesy - every call is guarded so a busy audio session
 * costs the player the tune and nothing else.
 */

/** Well under the effects, so a pour is always heard over the music. */
const VOLUME = 0.3;

let player: AudioPlayer | null = null;
// Off until the saved preference arrives, so someone who turned music off never hears a bar
// of it while settings load.
let enabled = false;

function ensurePlayer(): AudioPlayer | null {
  if (player) return player;
  try {
    configureAudio();
    const created = createAudioPlayer(require('../../assets/sound/music.wav'));
    created.loop = true;
    created.volume = VOLUME;
    player = created;
    return player;
  } catch {
    return null;
  }
}

export function setMusicEnabled(value: boolean): void {
  enabled = value;
  if (value) resumeMusic();
  // Hand the native player back rather than holding an audio session open for something
  // the player has said they do not want.
  else releaseMusic();
}

export function resumeMusic(): void {
  if (!enabled) return;
  try {
    ensurePlayer()?.play();
  } catch {
    // Silence is an acceptable failure.
  }
}

export function pauseMusic(): void {
  try {
    player?.pause();
  } catch {
    // Already stopped.
  }
}

export function releaseMusic(): void {
  if (!player) return;
  try {
    // Pause first, then release. `remove()` only unregisters the player, so the tune played
    // on until the object happened to be garbage collected. Pausing stops it on the spot and
    // hands the audio session back; releasing then frees the native player.
    player.pause();
    player.release();
  } catch {
    // Already gone.
  }
  player = null;
}
