import { createAudioPlayer, setAudioModeAsync, type AudioPlayer } from 'expo-audio';

/**
 * The board's voice: short wooden knocks generated by scripts/generate-sounds.mjs.
 *
 * Sound is a courtesy, never a requirement. Every call here is guarded, because a device
 * with a busy audio session or no output route must cost the player their sound effects,
 * not their game.
 */

export type SoundName = 'lift' | 'place' | 'complete' | 'invalid' | 'win';

const sources: Record<SoundName, number> = {
  lift: require('../../assets/sound/lift.wav'),
  place: require('../../assets/sound/place.wav'),
  complete: require('../../assets/sound/complete.wav'),
  invalid: require('../../assets/sound/invalid.wav'),
  win: require('../../assets/sound/win.wav'),
};

/**
 * Two players per sound, used round-robin.
 *
 * A single player cannot overlap with itself, and pours can land faster than a sound
 * finishes - with one voice each, a quick sequence swallows its own feedback.
 */
const VOICES = 2;

let pools: Record<SoundName, AudioPlayer[]> | null = null;
let next: Record<SoundName, number> = { lift: 0, place: 0, complete: 0, invalid: 0, win: 0 };
let enabled = true;
let configured = false;

export function setSoundEnabled(value: boolean): void {
  enabled = value;
}

function configure(): void {
  if (configured) return;
  configured = true;
  // Respect the ringer switch - people play puzzle games in public - and mix rather than
  // interrupt, so a podcast keeps playing underneath.
  setAudioModeAsync({ playsInSilentMode: false, interruptionMode: 'mixWithOthers' }).catch(() => {});
}

function pool(): Record<SoundName, AudioPlayer[]> | null {
  if (pools) return pools;
  try {
    configure();
    const built = {} as Record<SoundName, AudioPlayer[]>;
    for (const name of Object.keys(sources) as SoundName[]) {
      built[name] = Array.from({ length: VOICES }, () => createAudioPlayer(sources[name]));
    }
    pools = built;
    return pools;
  } catch {
    return null;
  }
}

export function play(name: SoundName): void {
  if (!enabled) return;
  const voices = pool()?.[name];
  if (!voices) return;

  const index = next[name] % VOICES;
  next = { ...next, [name]: index + 1 };
  const player = voices[index];
  if (!player) return;

  try {
    // Rewind first: a player parked at the end of its clip will not replay otherwise.
    void player.seekTo(0).catch(() => {});
    player.play();
  } catch {
    // A failed sound must never interrupt a move.
  }
}

/** Release the native players. Called when audio is switched off in settings. */
export function release(): void {
  if (!pools) return;
  for (const voices of Object.values(pools)) {
    for (const player of voices) {
      try {
        player.remove();
      } catch {
        // Already gone.
      }
    }
  }
  pools = null;
}
