import { createAudioPlayer, setAudioModeAsync, type AudioPlayer } from 'expo-audio';

/**
 * The board's voice: short cartoon bloops, boinks and bells generated by
 * scripts/generate-sounds.mjs.
 *
 * Sound is a courtesy, never a requirement. Every call here is guarded, because a device
 * with a busy audio session or no output route must cost the player their sound effects,
 * not their game.
 */

export type SoundName =
  | 'lift'
  | 'place'
  | 'complete'
  | 'invalid'
  | 'win'
  | 'stuck'
  | 'undo'
  | 'restart'
  | 'tap'
  | 'star'
  | 'hint';

const sources: Record<SoundName, number> = {
  lift: require('../../assets/sound/lift.wav'),
  place: require('../../assets/sound/place.wav'),
  complete: require('../../assets/sound/complete.wav'),
  invalid: require('../../assets/sound/invalid.wav'),
  win: require('../../assets/sound/win.wav'),
  stuck: require('../../assets/sound/stuck.wav'),
  undo: require('../../assets/sound/undo.wav'),
  restart: require('../../assets/sound/restart.wav'),
  tap: require('../../assets/sound/tap.wav'),
  star: require('../../assets/sound/star.wav'),
  hint: require('../../assets/sound/hint.wav'),
};

/**
 * Players per sound, used round-robin.
 *
 * A single player cannot overlap with itself, and pours can land faster than a sound
 * finishes - with one voice each, a quick sequence swallows its own feedback. Stars stamp
 * three in a row faster than a ding rings out, so they get a third.
 */
function voicesFor(name: SoundName): number {
  return name === 'star' ? 3 : 2;
}

let pools: Record<SoundName, AudioPlayer[]> | null = null;
const next: Partial<Record<SoundName, number>> = {};
let enabled = true;
let configured = false;

export function setSoundEnabled(value: boolean): void {
  enabled = value;
}

/** One audio-session setup, shared with the music player. */
export function configureAudio(): void {
  if (configured) return;
  configured = true;
  // Respect the ringer switch - people play puzzle games in public - and mix rather than
  // interrupt, so a podcast keeps playing underneath.
  setAudioModeAsync({ playsInSilentMode: false, interruptionMode: 'mixWithOthers' }).catch(() => {});
}

function pool(): Record<SoundName, AudioPlayer[]> | null {
  if (pools) return pools;
  try {
    configureAudio();
    const built = {} as Record<SoundName, AudioPlayer[]>;
    for (const name of Object.keys(sources) as SoundName[]) {
      built[name] = Array.from({ length: voicesFor(name) }, () => createAudioPlayer(sources[name]));
    }
    pools = built;
    return pools;
  } catch {
    return null;
  }
}

export function play(name: SoundName): void {
  if (!enabled) return;
  const voices = pool()?.[name];
  if (!voices) return;

  const index = (next[name] ?? 0) % voices.length;
  next[name] = index + 1;
  const player = voices[index];
  if (!player) return;

  try {
    // Rewind, and only then play. `seekTo` is asynchronous but `play` is not, so calling the
    // two back to back starts a player still parked at the end of its last clip: it finishes
    // at once, the seek then leaves it paused at the start, and every other replay is silent.
    // The rewind costs about 16ms on a simulator.
    player
      .seekTo(0)
      .then(() => player.play())
      .catch(() => {});
  } catch {
    // A failed sound must never interrupt a move.
  }
}

/**
 * Create every player up front. A player made on first use is still loading its clip when it
 * is asked to play, so the first sound of a session would land late.
 */
export function preloadSounds(): void {
  if (enabled) pool();
}

/** Release the native players. Called when audio is switched off in settings. */
export function release(): void {
  if (!pools) return;
  for (const voices of Object.values(pools)) {
    for (const player of voices) {
      try {
        // Pause, then release. `remove()` only unregisters a player, so a sound already playing
        // ran on and the native player lingered until it happened to be garbage collected.
        player.pause();
        player.release();
      } catch {
        // Already gone.
      }
    }
  }
  pools = null;
}
